CREATE DATABASE IF NOT EXISTS TIMEREPORT DEFAULT CHARACTER SET utf8;
#DROP DATABASE TIMEREPORT;
USE TIMEREPORT;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)  ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS projects(
	id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    rate DECIMAL(10,2) NOT NULL DEFAULT(1.00),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS timereports (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    hours DECIMAL(10,2),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE CASCADE
)  ENGINE=INNODB AUTO_INCREMENT=1;

CREATE OR REPLACE VIEW user_projects AS
    SELECT 
        u.id as uid, p.id, p.name, p.rate, t.hours
    FROM
        users u
            INNER JOIN
        timereports t ON u.id = t.user_id
            INNER JOIN
        projects p ON t.project_id = p.id;